# train_validate
#python -m torch.distributed.launch --nproc_per_node=1 train_validate.py --train_data=/home/#ricardo/Documents/Generated_data/connector_grey_lab_train --test_data=/home/ricardo/Documents/#Generated_data/connector_grey_lab_test --object=05_02_03_04_02_10_connector_grey --epochs=240 #--batchsize=32 --outf=output/connector_grey_lab

# python -m torch.distributed.launch --nproc_per_node=1 train_validate.py --train_data=/home/ricardo/Documents/Generated_data/connector_grey_lab/corrected_colour_4_5_dif_ilu/train/ --test_data=/home/ricardo/Documents/Generated_data/connector_grey_lab/corrected_colour_4_5_dif_ilu/eval/ --object=05_02_03_04_02_10_connector_grey --lr=0.0001 --epochs=110 --batchsize=32 --outf=output/weights/connector_grey_corrected_colour_4_5_dif_ilu

# train
#python -m torch.distributed.launch --nproc_per_node=1 train.py --data=/home/ricardo/Documents/#Generated_data/connector_grey_lab/train_def --object=05_02_03_04_02_10_connector_grey --#epochs=120 --batchsize=32 --outf=output/weights/connector_grey_lab_50000

# Inference
#python inference.py --weights ../output/weights/connector_grey_lab/net_epoch_240.pth --#data ../../Documents/Generated_data/connector_grey_lab_test --object #05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey_test

#python inference.py --weights ../output/weights/connector_grey_corrected_colour/net_epoch_97.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/#ilumination_experiment/ilumination_recorded_dataset/#connector_gray_ND_ilumination0-1_2023-11-28-13-36-54_data/ --object #05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/#recorded_data1_corrected_colour/ilumination_recorded_dataset/#connector_gray_ND_ilumination0-1_2023-11-28-13-36-54_data/

# python inference.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_109.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/ilumination_experiment/ilumination_recorded_dataset/connector_gray_ND_ilumination1-1_2023-11-28-13-44-10_data/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/ilumination_recorded_dataset/connector_gray_ND_ilumination1-1_2023-11-28-13-44-10_data/

# python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_4_5_dif_ilu/net_epoch_86.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_4_5_dif_ilu/iluexp_ND_bm/

python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_87.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_88.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_89.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_90.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_91.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_92.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_93.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_95.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_96.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_97.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_98.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_99.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_3/net_epoch_100.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_3/iluexp_ND_bm/

python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_98.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_99.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_100.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_101.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_102.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_103.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_104.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_105.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_106.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_107.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_108.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_110.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_111.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_112.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_113.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_114.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_115.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_116.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_117.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_118.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_119.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
python inference_beliefmap.py --weights ../output/weights/connector_grey_corrected_colour_2/net_epoch_120.pth --data ../../Documents/Generated_data/connector_grey_lab/recorded_data/iluexp_ND/ --object 05_02_03_04_02_10_connector_grey --outf ../output/inference_results/connector_grey/corrected_colour_2/iluexp_ND_bm/
